### ISSUE TITLE
CDC Connectors history mode & deletions

### ISSUE THREAD

**Issue by psFried** [estuary/connectors#1070]
The idea is to have an endpoint configuration option that enables "history mode". When this option is enabled, the connector will add an `associative: false` annotation to discovered JSON schemas.

- We should enable this option by default
- Update wording on delta updates for OLAP materializations to "delta updates (history mode)"

**Comment by jgraettinger** [comment]
Adding to scope: add `delete` annotations on _meta/op `d` events to thread through end-to-end deletions.

**Comment by jgraettinger** [comment]
Currently, `associative: false` is only available for the `lastWriteWins` reduction annotation.

I've been trying to recall whether that was fully intentional, or whether it really ought to be available for the `merge` annotation as well. It doesn't seem like a _bad_ idea for it to work with `merge`. But I am noting just now, that it would also work fine to pick a sub-location within the larger document (such as `/_meta/op` and mark that as `{reduce: {strategy: lastWriteWins, associative: false}}`.

This works because any _sub_location which is non-associative will also cause the entire document to not be combined associatively at capture (only fully reduced at materialization).
