### ISSUE TITLE
improve materialization update delay

### ISSUE THREAD

**Issue by williamhbaker** [estuary/connectors#1182]
The "update delay" feature of OLAP SQL materializations is currently pretty simple: It will apply the delay if the current transaction is below number of keys as an approximation for when a backfill is occurring, and it will always skip the delay on the first transaction of the connector's invocation.

We have observed this sometimes doesn't work well. The first transaction of an invocation is often very small (which is why the delay is skipped), but then if there is a delay on the _next_ transaction it can make it look like the materialization isn't doing anything. Also, there are occasionally small transactions mixed in with other large backfill transactions for reasons I won't get into.

We should consider requiring some number of initial transactions to pass before applying the delay, and/or requiring a consecutive number of small transactions as the connector is running to start applying the delay.

https://github.com/estuary/connectors/pull/1117 will move the materialization transactor into the connectors repo, so that would make it easier to incorporate this delay into the transactor, if it makes sense to do so. We might also consider cancelling the delay if the number of load requests for the next concurrent transaction is above a threshold, which is what makes me think we might want to put it in the transactor. Note that this would not work for delta-updates materializations, and may not work well considering recent runtime optimizations to not send load requests for keys that are known to not yet exist in the destination.

**Comment by jgraettinger** [comment]
I think it's likely this really belongs in the runtime. Doing it in the connector ... works, but has the downsides you note, and also: the connector cannot tell that the task is trying to restart with a new configuration, but the runtime can. This frequently comes up as users make changes and then wonder why it's not immediately taking effect (current reason: because we're waiting for the non-runtime-cancelable update delay to elapse)
