### ISSUE TITLE
source-stripe-native: Continue on failures

### ISSUE THREAD

**Issue by jonwihl** [estuary/connectors#1782]
Source Stripe Native should continue when the access token does not have sufficient permissions for a stream.

![Image](https://github.com/user-attachments/assets/40bbc671-e132-44bb-adbf-7e08f5431753)

**Comment by Luishfs** [comment]
The above issue is being cause due to the credential used being a [stripe restricitive api key](https://docs.stripe.com/keys#create-restricted-api-secret-key). We currently do not support restrictive keys, only secret keys.
I will add the support for both keys discovery and this should fix the issue

**Comment by jonwihl** [comment]
Support added in #1834 : https://github.com/estuary/connectors/pull/1834/files
