### ISSUE TITLE
Source Zendesk Streams Hanging Indefinitely

### ISSUE THREAD

**Issue by dyaffe** [estuary/connectors#1880]
**Background**

Two streams had to be disabled in our latest Zendesk capture because they caused the capture to hang indefinitely:

`ticket_metric_events`, `ticket_metrics`

Message me if you need more details.

cc @Alex-Bair

**Comment by Alex-Bair** [comment]
`ticket_metric_events` - This is a very dense stream, and it takes a while for the backfill to complete. Especially if the start date is very far in the past. I can increase the number of documents per page from 100 to 1,000, and that will help some. The stream does read incrementally after the backfill completes.

`ticket_metrics` - The endpoint being used for this stream isn't appropriate for capturing changes. It returns a list of ticket metrics sorted in descending order of when a ticket was created, _not_ when a ticket is updated.
So, right now it's essentially doing a full refresh of all tickets. My current idea is that we could [sideload](https://developer.zendesk.com/documentation/ticketing/using-the-zendesk-api/side_loading/#supported-endpoints) the recently improved `tickets` stream to incrementally get the metrics for only updated tickets.

**Comment by dyaffe** [comment]
Cool, great that the `ticket_metric_events` stream is incremental.  

Does it make sense for `ticket_metrics` to function like that?  In any case, perhaps we should remove the stream til we can prioritize making it function better more reliably for larger Zendesk installations?

**Comment by Alex-Bair** [comment]
I think it makes sense to have `ticket_metrics` work by sideloading from the `tickets` stream. I actually just found a [Zendesk post](https://support.zendesk.com/hc/en-us/community/posts/4984355661466/comments/4988227418138) that suggests doing that to get `ticket_metrics` incrementally, so I feel pretty confident that it's the right approach.

I don't anticipate it will take too long to actually update `ticket_metrics` to function like this since I can reuse a lot of the existing code. We will have to backfill `ticket_metrics` since the cursor field will change, so it probably is a good idea to disable the stream for now then re-enable & backfill it when the update is merged.
