### ISSUE TITLE
Snowflake certificate error

### ISSUE THREAD

**Issue by psFried** [estuary/connectors#210]
When publishing a snowflake materialization, this error was observed:

```
waiting for logs...
WARN[0001] No connector protocol is specified in the image, using default: Airbyte 
ERRO[0032] connector proxy execution failed.            
ERRO[0032] running connector failed                      error="exit status 1" logSource="ghcr.io/estuary/materialize-snowflake:dev" operation=validate
file:///flow.json error at /materializations/estuary~1phil~1test-snowflake :
driver error while validating materialization estuary/phil/test-snowflake

Caused by:
    driver.Validate: exit status 1 with stderr:
    
    time="2022-05-25T21:37:11Z" level=info msg="opening Snowflake" account=bn92689 database=ESTUARY_DB role=ESTUARY_ROLE user=ESTUARY_USER warehouse=ESTUARY_WH
    building endpoint: opening Snowflake database: Post "https://bn92689.us-central1.snowflakecomputing.com:443/session/v1/login-request?databaseName=ESTUARY_DB&requestId=df8f67f5-1738-4309-b28f-cdec5434412b&request_guid=97ddd206-154f-4304-bfad-5e52aea89f0d&roleName=ESTUARY_ROLE&schemaName=estuary&warehouse=ESTUARY_WH": x509: certificate is valid for *.us-west-2.snowflakecomputing.com, *.us-west-2.aws.snowflakecomputing.com, *.global.snowflakecomputing.com, *.snowflakecomputing.com, *.prod1.us-west-2.aws.snowflakecomputing.com, *.prod2.us-west-2.aws.snowflakecomputing.com, not bn92689.us-central1.snowflakecomputing.com
    {"timestamp":"2022-05-25T21:37:42.720588665Z","level":"ERROR","error":"CommandExecutionError("flow materialize connector: failed with code 1.")","message":"connector proxy execution failed."}
    
FATA[0032] fatal error                                   err="1 build errors"
Copying file:///tmp/.tmpFrbHVU/builds/063adbe5d6f1a000 [Content-Type=application/octet-stream]...
/ [0 files][    0.0 B/248.0 KiB]                                                
/ [1 files][248.0 KiB/248.0 KiB]                                                
```

It seems to be an issue with the TLS certificate for snowflake's endpoint, which doesn't appear to be valid for the domain we're using. It might also be that we're using the wrong URL. Or something else. Happy hunting :bug:

**Comment by dyaffe** [comment]
After speaking with Johnny, it appears that this problem is likely due to the fact that we've checked whether Snowflake works with S3 but not GCP and I was using GCP.  We likely need to devote time to ensure that Snowflake works with GCP.

**Comment by saterus** [comment]
First, I don't think this is a certificate error. It looks like there was a configuration error combined with a bad error message from the snowsql client.

Specifically, this line in the original error report: `building endpoint: opening Snowflake database: Post "https://bn92689.us-central1.snowflakecomputing.com:443/rest/of/the/path`. This needs to include `us-central1.gcp`, rather than just `us-central1`. 

Right now, this can be accomplished by putting `us-central1.gcp` into the `Region` section of the configuration. 

![snowflake-config](https://user-images.githubusercontent.com/119613/172899980-e9338883-4683-4ac5-b3d5-12d5dddd5ea1.png)

That said, this is a complete showstopper unless the user figures this out themselves. What do we think about adding a separate `Cloud Provider` config option and making both `Region` and `Cloud Provider` required fields? This way we can guide the user towards constructing a valid configuration the first time around.
