### ISSUE TITLE
BigQuery & Redshift error during Apply with large number of bindings and large collection schema

### ISSUE THREAD

**Issue by dyaffe** [estuary/connectors#260]
**Problem**
I just tried to set up our tests for BQ and hit another issue.  I attempted to materialize all our data that is currently being captured into a new materialization and got this error:

```
time="2022-06-09T19:45:47Z" level=info msg="opening bigquery" bucket=dave-estuary-test-bucket bucket_path=big-test dataset=dave_big_test project_id=helpful-kingdom-273219 region=us-central1
time="2022-06-09T19:45:47Z" level=info msg="failed to query materialization spec (the table may not be initialized?)" err="not found" table=helpful-kingdom-273219.dave_big_test.flow_materializations_v2
applying schema updates: query: run: googleapi: Error 400: The query is too large. The maximum standard SQL query length is 1024.00K characters, including comments and white space characters., invalid
" logSource="ghcr.io/estuary/materialize-bigquery:dev" operation=apply
FATA[0003] fatal error                                   err="applying materialization "estuary/monitoring/bigquery": exit status 1 with stderr:

time="2022-06-09T19:45:47Z" level=info msg="opening bigquery" bucket=dave-estuary-test-bucket bucket_path=big-test dataset=dave_big_test project_id=helpful-kingdom-273219 region=us-central1
time="2022-06-09T19:45:47Z" level=info msg="failed to query materialization spec (the table may not be initialized?)" err="not found" table=helpful-kingdom-273219.dave_big_test.flow_materializations_v2
applying schema updates: query: run: googleapi: Error 400: The query is too large. The maximum standard SQL query length is 1024.00K characters, including comments and white space characters., invalid
"
```

**Comment by williamhbaker** [comment]
There's a couple of things here:

- First is that we try to execute all of the statements as a single query. Each binding results in a new `CREATE TABLE...` statement. We can batch these up and execute them in separate statements, since BigQuery doesn't support DDL within a transaction anyway.
- Even then, the entire materialization spec needs to get stored in a single `INSERT` statement. Large numbers of bindings with collections that have big schema can exceed the character limit even with that single statement which base64 encodes the materialization spec. This effects BigQuery with its 1024*1000 character limit, and would also effect Redshift which has a 1MB limit for its `VARBYTE` column if the number of bindings gets high enough.

I believe that a batching strategy can sufficiently handle the many `CREATE TABLE` statements. For the size of the encoded materialization spec I think we should reduce the amount of information we are storing in the endpoint, and only store the binding information needed validate changes. I looked at this some when evaluating moving the `materialize-sql` connectors to the old JSON protocol and it seemed doable. Once the next round of protocol changes is rolled out I think we can address this.

**Comment by williamhbaker** [comment]
One thing to note: For BigQuery, there is a hard limit of 100 tables that can be updated in a single transaction, so there's really no way to have a BigQuery materialization with more than 100 bindings currently.

**Comment by williamhbaker** [comment]
Calling this done since we are now exceedingly efficient at creating huge numbers of tables and/or executing table alterations during `Apply` RPCs, and `Apply` doesn't even happen in an interactive user session anymore. The noted BigQuery limit on tables in a single transaction remains, although it is not likely for that to be an issue in practice since source collections usually won't have 100 collections all with data to be read at the same time.
