### ISSUE TITLE
Enable non-Backfill Mode for CDC

### ISSUE THREAD

**Issue by dyaffe** [estuary/connectors#272]
**Problem** 
Users have to pull all their historical data when using MySQL or Postgres CDC right now.  It would be ideal to have an option to not do backfills that they could select.

**Proposed Solution**
Add a config variable called "Backfill" which defaults to selected to both the MySQL and Postgres captures.  If we can't have it default to selected, then we can change it to "No Backfill" and have it defaulted to not selected.

**Comment by willdonnelly** [comment]
Some initial thoughts:
1. Default-true booleans tend to cause more operational issues -- there's just a lot of ways things can go wrong and result in them becoming false by accident, and so I'd push for inverting that and having something like a "Skip Backfills" checkbox in the advanced settings.
2. Instead of a single checkbox impacting all tables, I wonder if it might be better to have a comma-separated list of table names for which backfills should be skipped? This would allow use-cases like "in general we'd be happy to have all the data but we have this one table that's 4TiB and we don't need historical data" without requiring two capture instances.
3. It's possible for the configuration to change across connector restarts, so there are a few edge cases to be worked out. Tentative proposal:
  - During startup any table in the `Pending` or `Backfill` states immediately transitions to `Active` if the "Skip Backfills" option is active (for that specific table, if it's a list of names).
    - Most likely this would take place immediately after the first watermark is reached, so that the behavior around metadata initialization remains unchanged.
  - Once this transition to the `Active` state happens it's irreversible -- the table is considered fully caught up and disengaging the checkbox won't cause us to go back and redo that work that was skipped.

Thoughts?

**Comment by willdonnelly** [comment]
Ideally this per-table configuration would be part of the resource / binding specification, but that doesn't currently work in the UI for captures and it would require a fairly large refactoring to use the Flow captures protocol rather than the Airbyte protocol, so for now I think an option in the capture configuration is still the way to go, but we should remember that this can be improved in the future.

**Comment by dyaffe** [comment]
(1) sounds good to me

For (2) as per the conversation we just had, sounds good as a short term solution where we're working towards the binding-based long term one.

(3) all sounds good to me and I like the idea of being able to stop a backfill.

**Comment by willdonnelly** [comment]
Uploaded https://github.com/estuary/connectors/pull/274 which I believe should work pretty well until we're able to move it over to the resource spec.

**Comment by willdonnelly** [comment]
This feature has been merged as https://github.com/estuary/connectors/pull/274 and is now present in the "Advanced" section for MySQL / PostgreSQL capture creation in the web UI.
