### ISSUE TITLE
Research support for CrateDB materializations

### ISSUE THREAD

**Issue by dyaffe** [estuary/connectors#418]
**Problem**
We'd like to determine for a client whether we can push to CrateDB. We know that there are some gotchas -- the biggest one being that Postgres calls a JSON object "json" and CrateDB calls it an "object".

The backup plan is to use Timescale DB, so it would be ideal to test out timescale to ensure it works as well.

**Comment by dyaffe** [comment]
**Problem**
We'd like to determine for a client whether we can push to CrateDB.  We know that there are some gotchas -- the biggest one being that Postgres calls a JSON object "json" and CrateDB calls it an "object".

The backup plan is to use Timescale DB, so it would be ideal to test out timescale to ensure it works as well.

**Comment by mdibaiee** [comment]
CrateDB: I got a simple collection from google-sheet to materialize to CrateDB, had to make the following changes to make it possible:
1. As we already knew, JSON type is not supported, so I changed it to `OBJECT` and `ARRAY` (So far only `OBJECT` was tested as `flow_document` is stored with that type)
2. CrateDB does not support `TEMPORARY` tables, so I had to change the Load phase logic so that it creates a normal table, and then cleans it up before committing the transaction.

You can find the changes here (I hacked it up just as an experiment): https://github.com/estuary/connectors/pull/419/files

This is not final, I have to test a lot more cases, and I already can see some new errors popping up after a restart:
```{"_meta":{"uuid":"0694ba3f-611e-11ed-8400-416a444f9708"},"shard":{"name":"estuary/mahdi-test-cratedb","kind":"materialization","keyBegin":"00000000","rClockBegin":"00000000"},"ts":"2022-11-10T17:35:10.567641564Z","level":"error","message":"shard failed","fields":{"error":"go.estuary.dev/E116: connector failed, with error: exit status 1\nwith stderr:\n\ntime=\"2022-11-10T17:35:03Z\" level=info msg=\"opening database\" address=tan-wilhuff-tarkin.aks1.eastus2.azure.cratedb.net database=doc user=admin\ntime=\"2022-11-10T17:35:10Z\" level=error msg=\"RunTransactions failed\" error=\"transactor.Load: load at index 0: ERROR: Relation 'doc.flow_load_key_tmp_0' unknown (SQLSTATE 42P01)\" fence=4 keyBegin=0 keyEnd=4294967295 materialization=estuary/mahdi-test-cratedb\ntransactor.Load: load at index 0: ERROR: Relation 'doc.flow_load_key_tmp_0' unknown (SQLSTATE 42P01)\nError: go.estuary.dev/E002: Failed to execute command: flow materialize connector: failed with code 1.\n"}}
{"_meta":{"uuid":"0694bb15-611e-11ed-8400-416a444f9708"},"shard":{"name":"estuary/mahdi-test-cratedb","kind":"materialization","keyBegin":"00000000","rClockBegin":"00000000"},"ts":"2022-11-10T17:35:10.567664424Z","level":"error","message":"shard failed","fields":{"error":"app.ConsumeMessage: caller protocol error: AddDocument is invalid in state 2"}}```
