### ISSUE TITLE
source-postgres: reconsider `FOR ALL TABLES` publication group

### ISSUE THREAD

**Issue by jgraettinger** [estuary/connectors#460]
Currently our connector will try to be helpful and automatically create a publication `FOR ALL TABLES` at startup (expecting this to fail if the named publication already exists). This makes the publication forward-compatible with future tables which may be bound by the capture.

However, this can cause problems for `UPDATE` or `DELETE` of tables having no primary key:
```
cannot delete from table "foobar" because it does not have a replica identity and publishes deletes
```

This is problematic because creating a CDC of a live database has the potential to impact its existing usages.
Ideally the connector would be more selective over the tables included in its publication group.

There is a work-around, which is to set `REPLICA IDENTITY FULL`, as in:
```
# alter table foobar replica identity full;
```

**Comment by willdonnelly** [comment]
Off the top of my head I see two paths for improving this:

1. Remove the `CREATE PUBLICATION` startup behavior entirely, require that the user set it up along with creating the replication user and whatnot, and mention in the docs that they may want to specify just the set of tables they intend to capture. This is similar to how we currently handle table read permissions, for instance.
2. Replace the current `CREATE PUBLICATION <name> FOR ALL TABLES` startup query with `CREATE PUBLICATION <name>` to make sure a default-empty publication exists and then `ALTER PUBLICATION <name> ADD TABLE <foo>, <bar>, <etc>` to add all currently-bound tables. Since it's `ADD TABLE` rather than `SET` the publication will grow to cover all tables that were bound to the capture at any point even if they're later removed, but this seems better than potentially having two captures clobber each other (if a user for some reason configures two captures with distinct replication slots but the same publication name).

**Comment by jgraettinger** [comment]
👍 to option 2) from me, seems like a sound approach.
