### ISSUE TITLE
Sheets Connector Issue

### ISSUE THREAD

**Issue by dyaffe** [estuary/connectors#485]
**Problem**
A connector has failed with the following message and I am unable to determine what's going on:\

```
completeRecovery: store.RestoreCheckpoint: opening transactions RPC: reading Opened: rpc error: code = Internal desc = connector failed (exit status: 1) with stderr:
sheet "commits_one" row 0 with row state PrevRound=20, NextRound=26, and loadRound=0: PrevRound must have been committed (less or equal to loadRound)
```

The task is named: `trial/archana/fct_wiki_user_info`

**Comment by mdibaiee** [comment]
First I'm trying to understand how materialize-google-sheets works, here is my understanding so far:

> ℹ️  Each row of data has a zero-indexed "state" document saved along with it. This zero-indexed state document is not visible to users when they look at the spreadsheet, but we can fetch it using the API. This is used to keep track of changes to a row.


1. In Prepare phase, we increment `round` by one, in subsequent steps of the current transaction we use this newly bumped round number. This round starts at one when the connector is run for the first time (a zero value means there has been no checkpoint so far). This round is then persisted in recoverylog as a checkpoint.
2. In Store phase, for each row that we want to insert, we start off with an initial `storedRow` struct as follows:
```
{
  PackedKey: <the row key>,
  NextRound: <current transaction round number>,
  NextDoc: <data given to us in store phase by runtime to be stored for this row in this transaction>,
  PrevRound: 0,
  PrevDoc: nil,
  cells: []CellData # the zero-indexed cell of each row holds our internal state, which is basically all the properties above
}
```

3. We compare each Store phase row with rows on the spreadsheet: if the store row has a corresponding row on the spreadsheet (their `PackedKey`s are equal), then we update the `storedRow` to include this previous state:
```
{
  PackedKey: <the row key>,
  NextRound: <current transaction round number>,
  NextDoc: <data given to us in store phase by runtime to be stored for this row in this transaction>,
  PrevRound: <previous round number that stored this row>,
  PrevDoc: <data that's in the row at the moment>,
  cells: []CellData # the zero-indexed cell of each row holds our internal state, which is basically all the properties above
}
```

4. We proceed to either update the existing row, or add a new row
5. On subsequent runs of the connector, we run a few checks against the checkpoint and internal states of rows of the spreadsheet and the bindings given to us, one of these checks is the cause of the error seen above (where `loadRound` is the round number of the new transaction that is starting):
```
case row.PrevRound > loadRound:
	err = fmt.Errorf("PrevRound must have been committed (less or equal to loadRound)")
```

This is essentially a sanity check that `PrevRound` of a row that has already been stored in the spreadsheet must not be greater than the round of the current transaction, if that happens, it means we have somehow been writing data to the spreadsheet with round N, but the checkpoint in the recoverylog has not been updated to reach round N and is somehow behind.

In this instance, the issue seems to be that `loadRound` is zero, which is a sign that the checkpoint might have been wiped for some reason.

## Scenario

I can imagine one potential scenario for this to happen:

1. I create a materialization to a spreadsheet S
2. I materialize some documents from collection C into this spreadsheet
3. I delete or disable my materialization in Flow, but the data in the spreadsheet stays there (which also includes the internal state)
4. I now create another materialization to the same spreadsheet S, from the same collection C, however because this is a new materialization, the recoverylog is empty, and so the round starts at zero. However there is some internal state stored in the zero cell of each row which indicates a round number.
5. The connector is confused how can the internal state point to a round that has not yet happened.

## Potential ways out of this

1. If `loadRound` is explicitly zero, we consider the materialization to be a new one and don't compare round numbers at all. This means you can start materializing to a sheet which you have materialized to before without issues, however it makes me uncomfortable to allow a connector to make the call to overwrite data that belongs to another materialization.
2. Provide a better error message that clarifies what this error actually means: it usually means the scenario described above has happened, and a way out of this is to change the sheet you are materializing to, or manually clear the existing sheet and re-try.

**Comment by jgraettinger** [comment]
👍 to all your findings here.

> I can confirm in this case, our customer did actually have two materializations to the same sheet, one of which was disabled at the time the other one was running.

Yep, it's _not_ valid to have multiple active materializations to the same sheet, and exactly this can occur for the reasons you outline.

I agree that the best course of action is to extend this sanity check error with more user-facing advice and detail about this class of error ("don't do that").

**Comment by oliviamiannone** [comment]
I'll add a blurb to this effect to the docs as well.
