### ISSUE TITLE
source-postgres: Improve captures of user-defined types

### ISSUE THREAD

**Issue by willdonnelly** [estuary/connectors#544]
- Actually capturing user-defined domain and enum types pretty much works today.
- Capturing user-defined tuple and range types needs better value translation, currently it's just stringifying the Postgres text representation of the data.
- Discovery needs to produce vaguely reasonable JSON schemas for domain/enum/tuple/range typed columns.

**Comment by williamhbaker** [comment]
I'm going to close this issue out since https://github.com/estuary/connectors/pull/675 has been merged which improved implemented discovery for enums and ranges, and domain types were already being discovered & captured.

That PR did not address discovery or capture of composite (tuple) types, which would take quite a bit more effort. I opened a separate issue specifically for that (https://github.com/estuary/connectors/issues/677) which includes details about what I found when I was exploring what it might take. For the moment it is not believed these types are very common and thus lower priority to improve handling for.
