### ISSUE TITLE
Handle Airbyte spec auth_type

### ISSUE THREAD

**Issue by dyaffe** [estuary/connectors#89]
This currently prevents us from running any airbyte connector that supports OAuth...which is most of them.  Ex. airbyte/source-google-sheets fails in this way.  Github fails in a slightly different way. 

We should do two things here:
 1. Research and write up a design for how we could implement OAuth with our current system
 2. auth_type has two sub categories -- firstly OAuth and secondly something related to API key sign in.  Our discover workflow should ignore OAuth and present the options under the other item.

**Comment by psFried** [comment]
@dyaffe 
With estuary/flow#351 connectors that happen to support OAuth should now work in Flow, just without OAuth support. I think I can address the questions about authentication.

The high level design for OAuth should ultimately be pretty similar to what Airbyte implemented. Any design that we come up with should at least be _compatible_ with the Airbyte implementation, to allow for using OAuth with connectors that are written to that spec. Also, the high level approach that they took actually seems pretty reasonable to me. To summarize their approach, they require the connector specification to include a json blob that describes how to interact with the identity provider The connector itself isn't directly involved in that interaction, but rather just provdes the configuration for it, and there's a generic server component that interprets that and handles all the OAuth interactions for all connectors. For reference, here's [version one](https://docs.google.com/document/d/1Dmddudw19w0ZNgm97m2KIRcVreuJs6Z965BObuV3fWU/edit#heading=h.g1t5kw6d1oh0) and [version two](https://docs.google.com/document/d/1NQxErM9I_tnnB-juQRGKtNtPhnEg6uE9QCaYcntcPV8/edit) of their tech specs. These are pretty specific to Airbyte, so not everything will translate exactly into Flow. For example, we may not want to have instance-wide connector config bindings as they did, since connector configs aren't quite as central in our data model. But I think that's all stuff we can figure out once this work is a little more imminent.

> auth_type has two sub categories

I'm not quite sure if I've interpreted this question right, so please correct me if this is off base. The `auth_type` is superceded by `auth_flow_type` under the new `advanced_auth` key. Currently, it only specifies the OAuth protocol version. `advanced_auth` is expected to be unspecified if you're not using oauth, which just means that any values that are needed in order to authenticate must be directly present in the config. So I think what you're getting at here is just that we should hide any of the config fields that are only applicable to the OAuth flows. This seems like a reasonable ask, and is probably _possible_. But it's also probably not going to be _easy_, and it may not be worth the effort since we do intend to support OAuth soon anyway. Happy to talk more on that, though.

**Comment by dyaffe** [comment]
All this makes sense and sounds good.  Thanks @psFried, your point about us not doing the work to hide this, but instead doing OAuth work is well taken.  

I will start to test connectors next week after this makes it's way to master.

**Comment by psFried** [comment]
This was resolved by estuary/flow#351. Closing.
